/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import tareaguerra.Juego;

/**
 *
 * @author Usuario
 */
public class PantallaInicio extends javax.swing.JFrame {
    public Juego juego;
    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        this.juego = new Juego();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_panel = new javax.swing.JPanel();
        cargar_btn = new javax.swing.JButton();
        crear_tropa_btn = new javax.swing.JButton();
        iniciar_btn = new javax.swing.JButton();
        fondo_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargar_btn.setBackground(new java.awt.Color(153, 153, 0));
        cargar_btn.setText("CargarJuego");
        cargar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_btnActionPerformed(evt);
            }
        });
        fondo_panel.add(cargar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 120, 50));

        crear_tropa_btn.setBackground(new java.awt.Color(153, 153, 0));
        crear_tropa_btn.setText("Crear Tropa");
        crear_tropa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_tropa_btnActionPerformed(evt);
            }
        });
        fondo_panel.add(crear_tropa_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 120, 50));

        iniciar_btn.setBackground(new java.awt.Color(153, 153, 0));
        iniciar_btn.setText("Iniciar Juego");
        iniciar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_btnActionPerformed(evt);
            }
        });
        fondo_panel.add(iniciar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, 50));

        fondo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo_trabajo.png"))); // NOI18N
        fondo_panel.add(fondo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 890, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar_btnActionPerformed

    private void crear_tropa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_tropa_btnActionPerformed
        PantallaLogin login = new PantallaLogin();
        login.juego = this.juego;
        login.setVisible(true);
    }//GEN-LAST:event_crear_tropa_btnActionPerformed

    private void cargar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar_btn;
    private javax.swing.JButton crear_tropa_btn;
    private javax.swing.JLabel fondo_lbl;
    private javax.swing.JPanel fondo_panel;
    private javax.swing.JButton iniciar_btn;
    // End of variables declaration//GEN-END:variables
}
