/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Guerreros.Aereos;
import Guerreros.Contacto;
import Guerreros.GrandesBestias;
import Guerreros.Heroes;
import Guerreros.MedianoAlcance;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tareaguerra.FileManager;
import tareaguerra.Guerrero;
import tareaguerra.Juego;

/**
 *
 * @author Tefy
 */
public class PantallaAdmin extends javax.swing.JFrame {
    
    Juego juego;


    public PantallaAdmin() {
        juego = new Juego();
        initComponents();
    }

    /**
     * Creates new form PantallaAdmin
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        comboBoxTipos = new javax.swing.JComboBox<>();
        lblGolpesXSeg = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblAparicion = new javax.swing.JLabel();
        txtVidaPj = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblImagen1 = new javax.swing.JLabel();
        btnImag1 = new javax.swing.JButton();
        txtGolpesXSegPj = new javax.swing.JTextField();
        lblImagen2 = new javax.swing.JLabel();
        txtImagen1 = new javax.swing.JTextField();
        txtImagen2 = new javax.swing.JTextField();
        txtCampos = new javax.swing.JTextField();
        txtAparicion = new javax.swing.JTextField();
        btnCrearPersonaje = new javax.swing.JButton();
        lbCampos = new javax.swing.JLabel();
        btnImag2 = new javax.swing.JButton();
        lblTituloAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setName("frmAdmin"); // NOI18N
        setResizable(false);

        pnlAdmin.setBackground(new java.awt.Color(153, 102, 0));

        lblTipo.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo:");

        lblNombre.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        comboBoxTipos.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        comboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aéreo", "Grandes Bestias", "Contacto", "Mediano Alcance", "Héroe" }));
        comboBoxTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTiposActionPerformed(evt);
            }
        });

        lblGolpesXSeg.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblGolpesXSeg.setForeground(new java.awt.Color(255, 255, 255));
        lblGolpesXSeg.setText("Golpes por segundo:");

        lblVida.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblVida.setForeground(new java.awt.Color(255, 255, 255));
        lblVida.setText("Vida:");

        lblAparicion.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblAparicion.setForeground(new java.awt.Color(255, 255, 255));
        lblAparicion.setText("Aparición:");

        txtVidaPj.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        lblImagen1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblImagen1.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen1.setText("Imagen 1:");

        btnImag1.setBackground(new java.awt.Color(153, 255, 102));
        btnImag1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        btnImag1.setText("Escoger imagen 1");
        btnImag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImag1ActionPerformed(evt);
            }
        });

        txtGolpesXSegPj.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        lblImagen2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lblImagen2.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen2.setText("Imagen 2:");

        txtImagen1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        txtImagen2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        txtCampos.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        txtAparicion.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N

        btnCrearPersonaje.setBackground(new java.awt.Color(255, 153, 51));
        btnCrearPersonaje.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        btnCrearPersonaje.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPersonaje.setText("Crear personaje");
        btnCrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPersonajeActionPerformed(evt);
            }
        });

        lbCampos.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lbCampos.setForeground(new java.awt.Color(255, 255, 255));
        lbCampos.setText("Campos:");

        btnImag2.setBackground(new java.awt.Color(153, 255, 153));
        btnImag2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        btnImag2.setText("Escoger imagen 2");
        btnImag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImag2ActionPerformed(evt);
            }
        });

        lblTituloAdmin.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        lblTituloAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloAdmin.setText("Creador de personajes");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImag1)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addComponent(lbCampos)
                                .addGap(18, 18, 18)
                                .addComponent(txtCampos))
                            .addComponent(btnImag2)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblImagen2)
                                .addGap(18, 18, 18)
                                .addComponent(txtImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxTipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblAparicion)
                                .addGap(18, 18, 18)
                                .addComponent(txtAparicion))
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblImagen1)
                                .addGap(18, 18, 18)
                                .addComponent(txtImagen1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblVida)
                                .addGap(18, 18, 18)
                                .addComponent(txtVidaPj))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .addComponent(lblGolpesXSeg)
                                .addGap(18, 18, 18)
                                .addComponent(txtGolpesXSegPj, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnCrearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addComponent(lblTituloAdmin)
                .addGap(55, 55, 55))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTituloAdmin)
                .addGap(27, 27, 27)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(comboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVida)
                    .addComponent(txtVidaPj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGolpesXSeg)
                    .addComponent(txtGolpesXSegPj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAparicion)
                    .addComponent(txtAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCampos)
                    .addComponent(txtCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen1)
                    .addComponent(txtImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImag1)
                .addGap(21, 21, 21)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen2)
                    .addComponent(txtImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImag2)
                .addGap(38, 38, 38)
                .addComponent(btnCrearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(601, 601, 601))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTiposActionPerformed

    private void btnCrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPersonajeActionPerformed
        String aparicion = txtAparicion.getText();
        String campos = txtCampos.getText();
        String golpesXSegPj = txtGolpesXSegPj.getText();
        String imagen1 = txtImagen1.getText();
        String imagen2 = txtImagen2.getText();
        String vida = txtVidaPj.getText();
        String nombre = txtNombre.getText();
        
        if (aparicion.length() > 0 && campos.length() > 0 && golpesXSegPj.length() > 0 && imagen1.length() > 0 && imagen2.length() > 0 && vida.length() > 0 && nombre.length() > 0){
            String tipo = (String)comboBoxTipos.getSelectedItem();
            int vidaNum = Integer.parseInt(vida);
            int aparicionNum = Integer.parseInt(aparicion);
            int campoNum = Integer.parseInt(campos);
            int ataqueXSegundoNum = Integer.parseInt(golpesXSegPj);
            Guerrero nuevo;
            
            if (tipo.compareTo("Aéreo") == 0){
                nuevo = new Aereos(imagen2, 0, nombre, vidaNum, imagen1, aparicionNum, campoNum, ataqueXSegundoNum);
                juego.guerrerosDisponibles.add(nuevo);
                FileManager.writeObject(juego.guerrerosDisponibles, "src\\DatosGuardados\\GuerrerosDisponibles.dat");
            }
            else if (tipo.compareTo("Grandes Bestias") == 0){
                nuevo = new GrandesBestias(imagen2, 0, nombre, vidaNum, imagen1, aparicionNum, campoNum, ataqueXSegundoNum);
                juego.guerrerosDisponibles.add(nuevo);
                FileManager.writeObject(juego.guerrerosDisponibles, "src\\DatosGuardados\\GuerrerosDisponibles.dat");
            }
            else if (tipo.compareTo("Contacto") == 0){
                nuevo = new Contacto(imagen2, 0, nombre, vidaNum, imagen1, aparicionNum, campoNum, ataqueXSegundoNum);
                juego.guerrerosDisponibles.add(nuevo);
                FileManager.writeObject(juego.guerrerosDisponibles, "src\\DatosGuardados\\GuerrerosDisponibles.dat");
            }
            else if (tipo.compareTo("Mediano Alcance") == 0){
                nuevo = new MedianoAlcance(imagen2, 0, nombre, vidaNum, imagen1, aparicionNum, campoNum, ataqueXSegundoNum);
                juego.guerrerosDisponibles.add(nuevo);
                FileManager.writeObject(juego.guerrerosDisponibles, "src\\DatosGuardados\\GuerrerosDisponibles.dat");
            }
            else if (tipo.compareTo("Héroe") == 0){
                nuevo = new Heroes(imagen2, 0, nombre, vidaNum, imagen1, aparicionNum, campoNum, ataqueXSegundoNum);
                juego.guerrerosDisponibles.add(nuevo);
                FileManager.writeObject(juego.guerrerosDisponibles, "src\\DatosGuardados\\GuerrerosDisponibles.dat");
                ArrayList <Guerrero> guerreros = (ArrayList <Guerrero>) FileManager.readObject("src\\DatosGuardados\\GuerrerosDisponibles.dat");
                for (int i = 0; i < guerreros.size(); i++){
                    System.out.println(guerreros.get(i).toString());
                }
            }

            
        }
        else{
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearPersonajeActionPerformed

    private void btnImag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImag1ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.FILES_ONLY);
        f.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        f.setAcceptAllFileFilterUsed(false);
        f.showOpenDialog(this);
        String imagen1 = f.getSelectedFile().getAbsolutePath();
        txtImagen1.setText(imagen1);
    }//GEN-LAST:event_btnImag1ActionPerformed

    private void btnImag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImag2ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.FILES_ONLY);
        f.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        f.setAcceptAllFileFilterUsed(false);
        f.showOpenDialog(this);
        String imagen2 = f.getSelectedFile().getAbsolutePath();
        txtImagen2.setText(imagen2);
    }//GEN-LAST:event_btnImag2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPersonaje;
    private javax.swing.JButton btnImag1;
    private javax.swing.JButton btnImag2;
    private javax.swing.JComboBox<String> comboBoxTipos;
    private javax.swing.JLabel lbCampos;
    private javax.swing.JLabel lblAparicion;
    private javax.swing.JLabel lblGolpesXSeg;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloAdmin;
    private javax.swing.JLabel lblVida;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JTextField txtAparicion;
    private javax.swing.JTextField txtCampos;
    private javax.swing.JTextField txtGolpesXSegPj;
    private javax.swing.JTextField txtImagen1;
    private javax.swing.JTextField txtImagen2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVidaPj;
    // End of variables declaration//GEN-END:variables


}

